spring:
  application:
    name: server
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    jpa:
      hibernate:
        ddl-auto: create
  profiles:
    include:
      - spotify
      - google
      - kakao
      - jwt
logging:
  level:
    root: trace
