spring:
  application:
    name: server
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create-drop
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true
        globally_quoted_identifiers: true
        globally_quoted_identifiers_skip_column_definitions: true
      dialect: org.hibernate.dialect.MySQL8InnoDBDialect
  profiles:
    include:
      - spotify
      - oauth
      - jwt
      - cloud
logging:
  level:
    root: debug
    org:
      hibernate:
        SQL: off
client-info:
  host: "http://localhost:3000"

