spring:
  application:
    name: server
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;NON_KEYWORDS=USER
    username: sa
    password:
    jpa:
      hibernate:
        ddl-auto: create
  profiles:
    include:
      - spotify
      - oauth
      - jwt
logging:
  level:
    root: trace
client-info:
  host: "https://localhost:3000"

