spring:
  application:
    name: server
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;NON_KEYWORDS=USER
    username: sa
    password:
    jpa:
      hibernate:
        ddl-auto: create
  profiles:
    include:
      - spotify
      - oauth
      - jwt
      - cloud
  jackson:
    property-naming-strategy: SNAKE_CASE
logging:
  level:
    root: debug
client-info:
  host: "http://localhost:3000"

